### ISSUE TITLE
Primer nivel! [Codecks]

### ISSUE THREAD

**Issue by doctorhibert** [gamerevar/proyecto-comunitario-1-gd#66]
**Primer nivel**

**$139: Mapas: donde comenzará? bosque? pantano? ruinas? (En el templo del final)
En qué lugar del mapa comienza el jugador. (En la puerta)
Qué armas tiene? (Todos incluyendo enemigos tienen rifles)
Tiene $136: Team ? (Hay 3 jugadores,  con rango largo, medio y corto respectivamente)
Cuántos $128: Enemigos hay? (4 para empezar)
Qué tipos de $128: Enemigos?** (Guardianes del templo)

** https://gamerev.codecks.io/decks/4-game-design/card/135-primer-nivel.**

Mapas

Necesitamos saber los mapas como serán.

Cuántos tiles tendran largo x ancho? (Modular)
Qué tipos de terreno habrá? (Terreno caminable, terreno no caminable, cobertura media y cobertura entera

Jugador (3 soldados)
Vida? Cantidad? (5 HP, 4HP y 3HP respectivamente)
Stats? (Speed 6, 5, 4 respectivamente. Range 5, 10, 15 respectivamente, daño 1-4, 1-3 y 1-2 respectivamente
Etc

Team
El jugador tendra equipo como en X-COM? (Sí, 3 por ahora, posiblemente 4 si agregamos melee)
En cada nivel comenzará con el mismo equipo? (Por ahora sí, aunque estaría bueno agregar más armas y opciones)
Si mueren, reviven? Se pueden revivir? Mueren para siempre (estaría bueno!)? (Revivible en el nivel por un tiempo limitado y veces limitadas, el personaje revivido tiene un max HP limit. Si se termina el timer el personaje no está por el resto del mapa.

Armas
Qué armas tendrá el jugador o su $136: Team? (Por ahora todos el mismo rifle, aunque nos gustaría agregar más)
Tendrán munición? (Munición infinita pero cargadores limitados. El rifle tiene 2 tiros, y despues de eso hay que usar 1AP para recargarlo. Se pueden regargar infinitas veces)
Qué pasa si se acaba esa munición?

Hit chance
Hay que aclarar como se van a manejar las chances de hit que va a tener cada unidad. (El juego se maneja en un sistema binario de modificadores en incrementos de 25%. Los modificadores o los tenés o no los tenés y agregan o restan 25% cada uno. Entonces se parte de un 100% de pegar, y se resta 25% por estar muy lejos, un 25% porque el enemigo está en low cover, entonces tenemos un 50% de pegar. 

Cutscenes
Las transiciones entre nivel y nivel se realizarán en una escena aparte donde veremos como los $125: Soldados viajan en un vehículo militar entre punto de interés y punto de interés. (Gif loopeado del auto moviendose, y una caja de texto donde ponemos el dialogo y menúes si son necesarios)

**Comment by doctorhibert** [comment]
Agrejar tarjeta: "Stats"
Personaje 1: Short range
HP: 5
Speed: 6
Range: 5
Personaje 2: Medium range
HP:4 
Speed: 5
Range 10:
Personaje 3: Long range
HP: 3
Speed: 4
Range: 15

**Comment by doctorhibert** [comment]
Agregar nueva carta:
Cámara: No se puede hacer zoom ni rotar por ser pixel art, pero se puede panear con wasd o moviendo el mouse al borde de la pantalla.

**Comment by jh62** [comment]
Los tipos de terreno "cobertura media" y "cobertura completa" creo que es mas conveniente tratarlos como objetos. El terreno serian los tiles del tilemap que son todos el mismo ancho x alto. Un árbol por ejemplo bloquearía parcialmente por ahi, pero no se puede representar en un tilemap, sino que es una entidad que va por encima.

**Comment by jh62** [comment]
> Agrejar tarjeta: "Stats"
> Personaje 1: Short range
> HP: 5
> Speed: 6
> Range: 5
> 
> Personaje 2: Medium range
> HP:4
> Speed: 5
> Range 10:
> 
> Personaje 3: Long range
> HP: 3
> Speed: 4
> Range: 15

Se agrego la card Stats, pero genérica. Esta indica los stats universales para todas las unidades, que son estos que detallas acá. Luego cada unidad va a tener su número específico para cada uno.

**Comment by jh62** [comment]
> Agregar nueva carta:
> Cámara: No se puede hacer zoom ni rotar por ser pixel art, pero se puede panear con wasd o moviendo el mouse al borde de la pantalla.

Excelente. Puedo sugerir agregar paneo con botón derecho del medio apretado tambien?
