### ISSUE TITLE
Íconos de Modifiers

### ISSUE THREAD

**Issue by jh62** [gamerevar/proyecto-comunitario-1-gd#69]
# Íconos de Modifiers

![](https://media.discordapp.net/attachments/698387941537349692/793348232976662548/chrome_ZcElEfnN3I.png?width=567&height=134)

Estaría bueno incluir a futuro que los modificadores del _hit chance_ aparezcan en forma de ícono o texto como en X-COM. Creo que texto es más claro y rápido, ya que los íconos hay que hacerles hover una y otra vez para leer la descripción hasta aprenderlos.

Esta es una idea a futuro y no tiene que ser resuelta inmediatamente. Abro el hilo para futuro referencia.

**Comment by gamerevar** [comment]
test

**Comment by gamerevar** [comment]
test
