### ISSUE TITLE
Nueva entrada! [Codecks]

### ISSUE THREAD

**Issue by Ecoabismo** [gamerevar/proyecto-comunitario-1-gd#70]
**Arte**

**Tile Sizes**

**@Ferchiman ver junto a @azagaya el tamaño de los tiles que se van a utilizar en el juego.*

**https://gamerev.codecks.io/decks/6-arte/card/14s-tile-sizes**

Elegimos tiles de 64x32 isométricos. Los sprites de personajes humanoides tendrán 64x96. Adjuntamos ejemplos que sirven como referencia.

![Personajref](https://user-images.githubusercontent.com/40045009/103314205-1274cf80-4a01-11eb-9390-6b016e92ca4e.png)
![Tiles64x32](https://user-images.githubusercontent.com/40045009/103314208-13a5fc80-4a01-11eb-8fa1-fa41c0c3c221.png)

![Silueta64x96](https://user-images.githubusercontent.com/40045009/103314421-cfffc280-4a01-11eb-87aa-94cfad039f6b.png)
![Weapon](https://user-images.githubusercontent.com/40045009/103314424-d0985900-4a01-11eb-8841-b8d4077b9c5c.png)
![Personaje](https://user-images.githubusercontent.com/40045009/103314425-d130ef80-4a01-11eb-9bc2-30f84cde0da6.png)

![BaseTile64x32ex](https://user-images.githubusercontent.com/40045009/103314408-c4140080-4a01-11eb-9fbb-42679349b827.png)

![BaseTile64x32](https://user-images.githubusercontent.com/40045009/103314409-c4ac9700-4a01-11eb-8ddb-e3f9b9904173.png)

**Comment by gamerevar** [comment]
Publicado!!!
