### ISSUE TITLE
Tile sizes [Codecks]

### ISSUE THREAD

**Issue by Ecoabismo** [gamerevar/proyecto-comunitario-1-gd#73]
**Game design document**

**Tile sizes**

**Descripción de la tarjeta**

**https://gamerev.codecks.io/decks/11-game-design-document/card/15k-tile-sizes**

Los tile sizes son de 62x31
Lo personajes humanoides son de 62x93

Y agregarlo en arte también?

**Comment by gamerevar** [comment]
Agregado a arte.
