### ISSUE TITLE
Comenzar con la escena del cursor para definir Paths [Tarea]

### ISSUE THREAD

**Issue by azagaya** [gamerevar/proyecto-comunitario-1-gd#74]
**Descripción del feature**
Implementar un cursor que se ajuste a un tile de acuerdo con la posición del mouse. Debería debería detectar input events. Si se hace click sobre un tile en el que hay un personaje aliado (Un soldado) que almacene una referencia a ese soldado en una variable, por ejemplo `current_unit`. Los soldados probablemente sean `Area2D`, y nos permite seguir detectando eventos, raycast, etc. Por lo tanto, el cursor debería tener un Area2D para detectar objetos. El mouse se moverá libremente, pero el cursor implementado se ajustará siempre a la coordenada del tile (ver función `world_to_map` del `TileMap`). Este cursor dependerá del TileMap del lvl, por lo que seríá bueno dejar un export con el path hacia el `TileMap`, o sino se podría definir que el cursor sea siempre hijo directo del TileMap, y usar `get_parent()`. También necesitará una referencia al Navigation2D del lvl.

En esta primera etapa, lo que se busca es lograr tener un cursor que se ajuste a un tile, que con click izquierdo pueda seleccionar una unidad que este en el tile seleccionado, y con click derecho obtenga el simple path del navigation desde la posición de la unidad, hasta el tile donde se hizo click derecho. Luego, podrían ajustarse todos los vectores del pool que devuelve el simple path del navigation, a coordenadas enteras de tiles, y ese path será pasado a las unidades para que se muevan.

**Razón del feature**
Para no complejizar las unidades y personajes con los cálculos de movimiento o de selección, se implementan esas features en un cursor. La unidad simplemente recibiría instrucciones de este cursor.

**Implementación del feature**
Podría ser un Sprite, con un Area2D de hijo para detectar unidades.

**Comment by LeandroCuello** [comment]
Me gustaría tomar esta tarea pero antes quiero proponer un par de cosas.
Podría usar la clase AStar? La ventaja de esta clase es que no vamos a tener que estar definiendo los navigations de cada tile Y podríamos tomar todos los tile en los que se puede caminar dependiendo su nombre (por ejemplo llamándolos walkable_1). También esta función ya esta preparada para ser usada con tiles y mandar el path al jugador seria tan fácil como get_point_path(start, finish).
Por último estaba pensado que se podría hacer una escena con el tile map y agregar funciones que guarden la información de cuales tiles son coberturas, media cobertura, transitables y sus vecinos.
Propongo esto porque me pareció más escalable y cómodo, pero talvez no sea así.

**Comment by gamerevar** [comment]
Para un juego por turnos no sé la verdad sí A-Star sería más simple, pero no le veo nada de malo en usarlo. Yo personalmente prefiero A-Star por como me ha resultado en uso entre ambos. 

Con respecto al tipo de tile, se puede usar un diccionario o algo por estilo como referencia de que es cada uno.
