### ISSUE TITLE
Crear un script base para unidades [Tarea]

### ISSUE THREAD

**Issue by azagaya** [gamerevar/proyecto-comunitario-1-gd#75]
**Descripción del feature**
Crear un script, con `class_name Unit`, en el cual estarán todos los métodos comunes a las unidades, y sus stats. Por ejemplo, toda unidad tiene segun game design, speed, health y range. Además, toda unidad debería tener una función `move` que, dado un `PoolVector2Arra` desde el cursor (ver #74) proceda a moverse según las coordenadas en ese pool.
Debería heredar de Area2D, si vamos a usar eso para las unidades, o del nodo que corresponda.

Por ahora lo dejaríamos en eso, luego seguiremos agregandole features.

**Razón del feature**
Es útil que las unidades que tienen metodos y stats en comun, tengan una clase base, para no repetir código.

**Comment by LeandroCuello** [comment]
Creo que si ya se va a agreagar la variable range, faltaria la variable damage que guarde 2 numeros para el daño maximo y el daño minimo. En estas tarjetas se puede ver los stats [$155](https://gamerev.codecks.io/card/155-unidad-de-rango-largo), [$156](https://gamerev.codecks.io/card/156-unidad-de-rango-medio) y [$157](https://gamerev.codecks.io/card/157-unidad-de-rango-corto).

**Comment by azagaya** [comment]
Si. Hay que agregar eso tmb.

**Comment by azagaya** [comment]
Resuelto en #90
