### ISSUE TITLE
Crear escena base para los niveles [Tarea]

### ISSUE THREAD

**Issue by azagaya** [gamerevar/proyecto-comunitario-1-gd#76]
**Descripción del feature**
Algo útil es crear una escen base con todos los nodos sí o sí necesarios para un nivel, y luego heredar de ella para hacer niveles específicos.

**Razón del feature**
Esto permite que cuando tengas que hacer un nivel particular, no sea necesario volver a agregar toda la estructura básica del mismo, y además fuerza cierta organización cuando alguien que no haya hecho un nivel antes, quiera hacer uno.

**Implementación del feature**
El nivel debería tener por ahora el siguiente tree:

```
Node2D
|--> YSort
       |--> TileMap
              |--> Cursor (ver #74)
       |--> AliedUnits (YSort)
       |--> EnemyUnits (YSort)
...
```

AliedUnits y EnemyUnits serían nodos 2d, donde por organización agregariamos los soldados y los enemigos respectivamente. Luego se pueden ir agregando otros (Objects, Projectiles, etc).

El tilemap podría estar seteado en isometrico con un size de 62x31, ya que todos los tilesets serán así.

**Comment by jh62** [comment]
Me parece que la estructura hay que cambiar los nodos _AlliedUnits_ y _EnemyUnits_ de _Node2D_ a **YSort** porque sino el YSort padre solo va a mover los Node2D y no sus hijos. Me refiero a esto:

![BNB1SNYR4a](https://user-images.githubusercontent.com/22467336/103390389-f3ef0100-4af2-11eb-8a0b-8511d76b7613.gif)

En cambio reemplazando los Node2D por YSort:

![IdMDJfshGg](https://user-images.githubusercontent.com/22467336/103390396-fc473c00-4af2-11eb-8a5d-d06c3a344efb.gif)

**Comment by azagaya** [comment]
Corregido

**Comment by azagaya** [comment]
Cerrado por #89
