### ISSUE TITLE
Line Of Sight [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#78]
# Line Of Sight

Aclarar cómo va a funcionar el rango de visión de las unidades.

Por ejemplo, en el _X-COM original_ si dentro del rango de visión una unidad esta en línea directa (sin obstáculos que obstruyan) de otra, esa unidad aparece en el mapa y además el HUD crea un indicador por cada enemigo avistado los cuales permiten centrar la cámara en cada uno haciéndoles click.

Sugeriría utilizar un simple raycasting con cierta longitud hacia todas las unidades enemigas que estén a cierta distancia de otras para hacer un chequeo simple al comienzo de cada turno.

### Referencias

[$14q](https://open.codecks.io/proyecto-comunitario-1-gd/decks/4-game-design/card/14q-line-of-sight)

**Comment by doctorhibert** [comment]
Me parece perfecto. También me parece más facil que en vez de hacer que sea todo negro lo que no descubriste como en el xcom original hacer que esté solo más oscuro y no puedas ver los enemigos.

**Comment by gamerevar** [comment]
Bien. Entonces se cierra el issue y se sigue con la mecánica descripta.
