### ISSUE TITLE
Stats de las unidades [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#80]
# Stats de las unidades

Si bien las stats de las unidades fueron especificadas, aclarar puntualmente que significa cada uno, ya que son claros, pero pueden representar diferentes cosas para el que lo lee.

* HP (vida, este es obvio)
* Speed (cantidad de tiles que se mueve la unidad por AP. Algo mas?)
* Range (rango máximo de ataque? de visión?)

### Referencias

[Codecks $15e](https://open.codecks.io/proyecto-comunitario-1-gd/decks/4-game-design/card/15e-stats-de-las-unidades)

**Revisar los comentarios en Codecks**

**Comment by doctorhibert** [comment]
Range sería el rango óptimo del arma. Si están a más tiles que el range tienen un -25% a pegar. La vision por ahora creo que debería ser un raycast colectivo de todos los personajes jugables, porque no creo que tengamos mapas tan grandes.

**Comment by jh62** [comment]
Excelente.
