### ISSUE TITLE
Tipos de terreno [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#82]
# Tipos de terreno

Aclarar los tipos de terreno caminables y no caminables.

1. Caminables: grass, dirt, etc...
2. No caminables: water, etc...

### Referencias

[Codecks](https://open.codecks.io/proyecto-comunitario-1-gd/decks/4-game-design/card/14x-tipos-de-terreno)

**Comment by doctorhibert** [comment]
Por ahora los no caminables serían solamente las paredes/obstáculos y las cosas que no tengan tiles

**Comment by LeandroCuello** [comment]
Quiero mencionar, que dependiendo que se decida en [este issue](https://github.com/gamerevar/proyecto-comunitario-1-gd/issues/94) a nivel programacion va a ser muy facil tener tiles que cuesten mas puntos de movimiento, limitando el movimiento de las unidades.
un ejemplo que se me ocurre podrían ser tiles con agua, pero! serían más animaciones, efectos de sonidos, etc.
se pueden buscar excusas como que en el templo hay lugares en el suelo con gravedad aumentada... porque si. y eso seria mas facil solo tendríamos que cambiar el color de los tiles.

**Comment by doctorhibert** [comment]
Me parece bien, eso se puede hacer más adelante.

**Comment by gamerevar** [comment]
Bueno. Cerramos este issue ya que se determiaron los tiles caminables/no caminables. Mas adelante se hilará más fino.
