### ISSUE TITLE
Escenearios [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#83]
# Escenarios (niveles)

Determinar los escenarios que atravesará el jugador en su recorrido por la historia.

### Referencias

[Codecks](https://open.codecks.io/proyecto-comunitario-1-gd/decks/4-game-design/card/151-escenarios-niveles)

**Comment by doctorhibert** [comment]
La idea sería tener diferentes niveles en diferentes partes del mundo, pero para el principio solo vamos a tener 3 niveles, 2 adentro del templo y 1 afuera.

**Comment by jh62** [comment]
Ok, lo cierro porque van a empezar por el templo segun pude ver. Lo vemos mas adelante.
