### ISSUE TITLE
Save Game [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#85]
# Save Game

* Determinar cómo y cuándo se puede salvar una partida.
* Hay checkpoints?
* Las probabilidades de la partida deben ser siempre las mismas o pueden cambiar (random seed o seed fijo).
 
etcétera

### Referencias

[Codecks](https://open.codecks.io/proyecto-comunitario-1-gd/decks/4-game-design/card/15y-save-game)

**Comment by LeandroCuello** [comment]
Me parece que para la etapa de la no va a hacer falta. Pero para más adelante, cada vez que se pase de nivel y si se desbloquea una mejor.
(Suponiendo que hagamos mapas chicos)

**Comment by doctorhibert** [comment]
Estaría muy bueno poder guardar y recargar en cualquier turno tuyo. El team de programación tendría que decidir cuan dificil es y si vale la pena.

**Comment by azagaya** [comment]
No es mayor problema. Guardar luego de cada nivel es mas simple porque hay cosas que ni tenes que guardar (estado de los jugadores y enemigos, por ejemplo). Pero igual no seria problema. A veces los juegos si podes guardar en cada momento dejan esa sensacion de que podes pasar a prueba y error.. pero si guardas poco puede ser frustrante cuando se pierde..

**Comment by doctorhibert** [comment]
Aunque sea creo que sería bueno para testear, despues se puede tweakear o hacerlo solo autosave para que no pierda la dificultad.

**Comment by jh62** [comment]
> No es mayor problema. Guardar luego de cada nivel es mas simple porque hay cosas que ni tenes que guardar (estado de los jugadores y enemigos, por ejemplo). Pero igual no seria problema. A veces los juegos si podes guardar en cada momento dejan esa sensacion de que podes pasar a prueba y error.. pero si guardas poco puede ser frustrante cuando se pierde..

Si las misiones no son muy largas, yo opino lo mismo: salvar entre nivel y nivel (preguntar salvar luego del cutscene).

Bueno, cerramos el issue poniendo que se puede salvar al comienzo del turno del player, cuando todas las unidads tienen 100% de AP's. Más que nada es útil saber esto para ver q tipo de información es necesaria guardar.
