### ISSUE TITLE
Rango de las unidades

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#91]
# Rango de las unidades

Aclarar las diferencias entre las unidades de rango largo, medio y corto. Tienen sanguínea ventaja a excepción del alcance? Tienen algún ataque diferente? Que diferencia hay en utilizar una u otra? Ventajas? 

### Referencias o links

[Enemigos](https://open.codecks.io/proyecto-comunitario-1-gd/decks/11-game-design-document/card/128-enemigos) 

[Unidades del jugador](https://open.codecks.io/proyecto-comunitario-1-gd/decks/11-game-design-document/card/154-team-del-jugador)

**Comment by doctorhibert** [comment]
Más que nada es para darle más variedad al jugador, que cada uno de los tres personajes se comporten de manera diferente entonces así no pueden hacer siempre lo mismo con los tres.
 Me encantaría que cada personaje tenga una habilidad especial, como que el sniper pueda hacer headshot, que el medium range tenga un granada y el close range pueda disparar después de correr, pero por ahora no tiene sentido preocuparse por eso.
Cada personaje tiene su propio modo de jugarlo, etntonces no es una decisión de "a ver si me equipo una escopeta en esta misión", es "tengo un soldado con escopeta, entonces si no me acerco a los enemigos con él voy a estar errando constantemente".
Lo del daño habría que balancearlo, honestamente no sé cuánto daño tendría que hacer cada uno, si hacer que la escopeta o el sniper hagan más daño o lo que sea. Acepto cualquier idea que tengan.

**Comment by jh62** [comment]
Q tal esto:

### Unidad de rango corto: 

* 9 disparos antes de recargar.
* El daño no es afectado por el _range_, pero si la puntería.

### Unidad de rango medio:

* 6 disparos antes de recargar.
*  Daño extra dentro de su _range_ de tiles. Cuanto más lejos de su _range_ se dispare, menos puntería.

### Unidad de rango largo:

* 3 disparos antes de recargar.
* Puntería constante dentro de su _max range_ de disparo. Posibilidad o chance de matar con 1 tiro de suerte cuanto más lejos este el _target_ (tipo, para incentivar a usar la unidad como sniper).

**Comment by doctorhibert** [comment]
Me parece un poco alto el número de tiros antes de recargar, pero probemoslo como queda ingame.

**Comment by jh62** [comment]
> Me parece un poco alto el número de tiros antes de recargar, pero probemoslo como queda ingame.

Dale. Puede ser que sean altos, aunque también depende mucho de la vida de los enemigos y con el hit chance de cada unidad.
