### ISSUE TITLE
Cámara [Tarea]

### ISSUE THREAD

**Issue by azagaya** [gamerevar/proyecto-comunitario-1-gd#92]
# Cámara

## Descripción
Sería una escena con root `Camera2D`. Debe tener un script que, cuando el mouse esté a cierta distancia de los bordes, se mueva en esa direccion, o en diagonal si esta cerca de una esquina. También puede moverse con WSAD.

 Además debería tener la funcionalidad de definir "anchors" y que la cámara se mueva a ellos (con un `Tween` por ejemplo, con easing). Durante el movimiento, la cámara no podría moverse con el mouse.

**Comment by jh62** [comment]
El PR se mergeo, no deberia estar abierta esta tarea. Se cierra.
