### ISSUE TITLE
Movimento diagonal [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-gd#94]
Describir movimientos diagonales cuántos AP cuestan. y como afecta eso al rango del personaje. Cómo referencia están las siguientes imágenes:

* Utilizando 1 AP

![unknown-7](https://user-images.githubusercontent.com/73669928/104111863-3b7d4600-52c6-11eb-8de0-de20cf1a6edd.png)

* Utilizando 2 AP:
![unknown-8](https://user-images.githubusercontent.com/73669928/104111870-47690800-52c6-11eb-996b-1b2b15890d3e.png)

**Comment by jh62** [comment]
El rango del personaje (visión) debería ser independiente de la cantidad de tiles que pueda moverse. Sino siempre van a tener que estar muy cerca de un enemigo para atacar.

**Comment by LeandroCuello** [comment]
> El rango del personaje (visión) debería ser independiente de la cantidad de tiles que pueda moverse. Sino siempre van a tener que estar muy cerca de un enemigo para atacar.

sisi pero el rango de movimiento no tiene nada que ver con la vision. los tiles verdes son las callisas a las que se puede mover. la diferencia es el costo de movimiento en diagonal.

**Comment by doctorhibert** [comment]
El costo de movimiento en diagonal debería ser 1, igual que cualquier otro movimiento.
